[project]
  authors         = [{ "name" = "Simon van Lierde", "email" = "30519500-simonvanlierde@users.noreply.gitlab.com" }]
  dependencies    = ["json5>=0.15.0"]
  description     = "pre-commit hook to check json files for syntax parseable as json5 (with comments)"
  license         = "MIT"
  name            = "check-json5"
  readme          = "README.md"
  requires-python = ">=3.10"
  version         = "1.1.0"

  [project.scripts]
    check-json5 = "pre_commit_hooks.check_json5:main"

[dependency-groups]
  dev = ["pre-commit>=4.6.0", "pytest>=8", "pytest-cov>=5", "ruff>=0.15.20", "ty>=0.0.56"]

[tool.ruff]
  fix            = true
  line-length    = 120
  target-version = "py313"

  [tool.ruff.format]
    docstring-code-format = true

  [tool.ruff.lint]
    extend-select = ["ALL"]
    fixable       = ["ALL"]

    # These rules are ignored to prevent conflicts with formatter or because they are overly strict
    ignore = [
      "D206",   # indent-with-spaces
      "D300",   # triple-single-quotes
      "E111",   # indentation-with-invalid-multiple
      "E114",   # indentation-with-invalid-multiple-comment
      "E117",   # over-indented
      "ISC001", # single-line-implicit-string-concatenation
      "ISC002", # multi-line-implicit-string-concatenation
      "RET504", # unnecessary-assign
      "W191",   # tab-indentation
    ]

    [tool.ruff.lint.per-file-ignores]
      "tests/**" = ["S101", "D103"]

    [tool.ruff.lint.pydocstyle]
      convention = "google"

[tool.uv]
  package = true
